### ISSUE TITLE
Great Preset!

### ISSUE THREAD

**Issue by dominikgeimer** [zaknes/tailwind-preset#7]
Hi,

i really like your clean and awesome tailwind preset! Thank you for that!

Just one question: What kind of svg Icons are you using in the signin/signup?

**Comment by zaknesler** [comment]
Hey!

You're very welcome! Keep on the lookout for an even cleaner design, haha. Hopefully I will be able to get to that soon.

The icons are from Steve Schoger's [Heroicons UI](http://www.steveschoger.com/2018/01/04/introducing-heroicons-ui/) pack. He also has [Zondicons](http://www.zondicons.com/) but they seemed a little too bold when I tried them before.

Take care!
