### ISSUE TITLE
v1.0 Support

### ISSUE THREAD

**Issue by DCzajkowski** [zaknes/tailwind-preset#9]
Are you planning to add support for Tailwind 1.0? Docs are already available here: https://next.tailwindcss.com

**Comment by zaknesler** [comment]
Yep! Working on it as we speak 😉

<img width="547" alt="Screen Shot 2019-04-19 at 5 30 02 PM" src="https://user-images.githubusercontent.com/7189795/56444909-cf280b00-62c8-11e9-8657-068f1b4373d9.png">

**Comment by DCzajkowski** [comment]
Great 💪
